# Docker Compose 파일 - Redis 서버 설정

services:
  redis:
    image: redis:7.2-alpine
    container_name: smart-factory-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=
    networks:
      - smart-factory-network

  # Redis 관리 도구 (선택사항)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: smart-factory-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - smart-factory-network

volumes:
  redis_data:
    driver: local

networks:
  smart-factory-network:
    driver: bridge
